# Generated by Django 3.2.3 on 2021-12-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=4)),
                ('snom', models.CharField(max_length=255)),
                ('scontact', models.CharField(max_length=255)),
            ],
        ),
    ]
